name: build_ErfanGSIs

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://96mqqbod00rne37j0bvi7vfobhcpjgrtgh1lk7fkm8l5kv2nmqlvu8nf.qc.dolfincdnx.cn:7843/xdispatch7396afc96ae1f539/bigota.d.miui.com/V13.1.22.9.28.DEV/miui_PSYCHE_V13.1.22.9.28.DEV_413a9c306d_12.0.zip?BSLuBan=eyJob3N0IjoiYmlnb3RhLmQubWl1aS5jb20iLCJic3JlcWlkIjoiN2M2MjRmZmFmNGU2NTgwM2FkMGQ5OWYyZTg3ODZjZDciLCJjYWNoZV9rZXkiOiJcL1YxMy4xLjIyLjkuMjguREVWXC9taXVpX1BTWUNIRV9WMTMuMS4yMi45LjI4LkRFVl80MTNhOWMzMDZkXzEyLjAuemlwIiwiZG5zX2hvc3QiOiJwZjAwMy52LmJzZ3NsYi5jbiIsImtleSI6ImY0YWU1N2JhNzhhZmFjMTY0YzAxMjBmMjg3ZTdmNGJjIiwidHMiOjE2NzMxODI2NzF9
  ROM_NAME: MIUI13-GSI-least
  BUILD_TYPE: Aonly
  TZ: Asia/Shanghai
  ARTIFACT_NAME: ErfanGSIs-test 

jobs:
  build:
    runs-on: macos-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd ErfanGSIs
              mkdir ./output
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd /ErfanGSIs
              mkdir upload
              sudo brew install p7zip 
              7z a -t7z -r ./upload/test.7z ./output/*
       
       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
           name: ${{ env.ARTIFACT_NAME }}
           path: |
                 "ErfanGSIs/output/*"
                 "ErfanGSIs/upload/test.7z*"
                 
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/upload
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./test.tar.gz

         
            
